var _tmr=_tmr||[];
(function(){function u(a,q,c){a.addEventListener?a.addEventListener(q,c,!1):a.attachEvent&&a.attachEvent("on"+q,c)}function h(){}function F(a){return(a=!m?void 0:m[a])&&v?a-v:void 0}function n(a,q){var d="id"in a?a.id:k,e="url"in a?a.url:location.href,b="referrer"in a?a.referrer:g.referrer,f="title"in a?a.title:g.title,d=("https:"==g.location.protocol?"https:":"http:")+"//top-fwz1.mail.ru"+(q?"/tracker":"/counter")+"?js=13"+(d?";id="+escape(d):"")+(e?";u="+escape(e):"")+(b?";r="+escape(b):"")+("start"in
a&&0<a.start?";st="+escape(a.start):"")+("gender"in a?";gender="+escape(a.gender):"")+("age"in a?";age="+escape(a.age):"")+(f?";title="+encodeURIComponent(f):"")+((w=c.screen)?";s="+w.width+"*"+w.height:"")+";vp=",b=e=0;g.documentElement&&(g.documentElement.clientWidth||g.documentElement.clientHeight)?(e=g.documentElement.clientWidth,b=g.documentElement.clientHeight):"number"==typeof c.innerWidth&&(e=c.innerWidth,b=c.innerHeight);d=d+(""+e+"*"+b)+";touch="+G+";hds="+H+";flash="+x+";sid="+B+";ver="+
C+";nt=";if(!m||!y)e="";else{e=[];e.push(y.type);e.push(y.redirectCount);e.push(v);for(b=0;b<D.length;b++)e.push(F(D[b]));e=e.join("/")}return d+e+";_="+Math.random()}function E(a,b){return("https:"==g.location.protocol?"https:":"http:")+"//top-fwz1.mail.ru/tracker?js=13;id="+a[0]+";e="+escape(b)+";sid="+B+";ids="+a.join()+";ver="+C+";_="+Math.random()}function I(){for(var a=0;a<p.length;a++){var b=p[a];(new Image).src=n(b,!0)+";e="+escape("PVT/15")}}function z(){_tmr.onload()}if("[object Array]"===
Object.prototype.toString.call(_tmr)){var c=window,d=navigator,g=document,w,k=0,C=60,r=[],A=0,s=0,l=[],B="xxxxxxxx".replace(/[x]/g,function(a){return(16*Math.random()|0).toString(16)}),p=[],t=0,G="ontouchstart"in c||1<(d.maxTouchPoints||d.msMaxTouchPoints)?"1":"0",H=c.devicePixelRatio||0,x="";if(d.plugins&&d.plugins["Shockwave Flash"])x=d.plugins["Shockwave Flash"].description.split(" ")[2];else if(c.ActiveXObject)try{var f=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),f=f.GetVariable("$version"),
f=f.split(" ")[1].split(","),x=f[0]+"."+f[1]}catch(J){}var d=c.performance||c.mozPerformance||c.msPerformance||c.webkitPerformance||{},m=d.timing||{},y=d.navigation||{},D="unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),v=!m?void 0:
m.navigationStart;h.prototype.pageView=function(a){"start"in a&&r.push(a);(new Image).src=n(a,!1);s=(new Date).getTime()};h.prototype.reachGoal=function(a){"goal"in a&&((new Image).src=n(a,!0)+(a.goal?";e="+escape("RG/"+a.goal):""))};h.prototype.itemView=function(a){if("id"in a||k)(new Image).src=("https:"==g.location.protocol?"https:":"http:")+"//ad.mail.ru/retarget/?counter="+(a.id||k)+"&list="+(a.list||"")+"&productid="+(a.productid||"")+"&pagetype="+(a.pagetype||"")+"&totalvalue="+(a.totalvalue||
0)+"&_="+Math.random()};h.prototype.processEvent=function(a){if("type"in a&&("pageView"!=a.type||"id"in a)){if(!k&&"id"in a&&"type"in a&&("pageView"==a.type||"reachGoal"==a.type))k=a.id;switch(a.type){case "pageView":this.pageView(a);break;case "reachGoal":this.reachGoal(a);break;case "itemView":this.itemView(a)}}};h.prototype.push=function(a){this.processEvent(a)};h.prototype.onload=function(){if(0<r.length){t=(new Date).getTime();for(var a=0,b;b=r[a];a++)(new Image).src=n(b,!0)+";e="+escape("RT/load")+
";et="+t;s=t;r=[]}setTimeout(I,15E3)};h.prototype.beat=function(){if(0!=l.length&&A){var a=(new Date).getTime(),b=a-A;if(!(12E4<b)){if(12E4<a-s)for(var c=0;c<p.length;c++){var d=p[c];(new Image).src=n(d,!0)+";e="+escape("RT/resend")+";et="+t+";active="+(b?"1":"0")}else(new Image).src=E(l,"RT/beat");s=a}}};h.prototype.unload=function(){0!=l.length&&((new Image).src=E(l,"RT/unload"))};h.prototype.activity=function(a){A=(new Date).getTime()};for(var d=new h,f=0,b;b=_tmr[f];f++)if(!k&&"id"in b&&"type"in
b&&("pageView"==b.type||"reachGoal"==b.type))k=b.id;for(f=0;b=_tmr[f];f++)"id"in b&&("type"in b&&"pageView"==b.type&&5>l.length)&&(l.push(b.id),p.push(b)),d.processEvent(b);_tmr=d;if("complete"===g.readyState)_tmr.onload();else c.addEventListener?c.addEventListener("load",z,!1):c.attachEvent?c.attachEvent("onload",z):c.onload=z;u(c,"beforeunload",_tmr.unload);if(l.length){setInterval(_tmr.beat,3E4);try{d=function(a){for(var b=0;b<a.length;b++)u(g,a[b],function(){_tmr.activity(a[b])})},d(["scroll",
"gesturechange","touchmove"]),d(["mousedown","mousemove","mouseup"]),u(c,"scroll",function(){_tmr.activity("scallback")})}catch(K){}}}})();
